### PR TITLE
DEFER: Improve usb thumb files

### PR DESCRIPTION
**Pull request by RobMackie**
This fix causes the presence of a "network.txt" on an inserted usb to trigger *both* the overwrite of "network.txt" with the network configi info  *and* the creation/overwrite of a local webpage named "fabmo.html". The webpage is emitted such that it has a direct link to fabmo on it. so that the user can double click on the "fabmo.html" and then click on the link and then go to their fabmo installation.

### CODE REVIEW

**Comment by obra** [comment]
#901 contains a duplicate implementation of this PR as part of a larger cleanup. So sorry for the duplication.

**Comment by kyle-kingsbury** [comment]
Ran the dev-checks. Tested whether network.txt and shopbotsupport.txt were populated with the correct information. Tested that fabmo.html is created and overwritten if already present, also network.txt is overwritten. 

During my testing yesterday the fabmo-log that is supposed to be exported to shopbotsupport.zip was not there, but today it is. One thing to note, after running dev-build.sh, I ^c out of "run dev" then "sudo systemctl start fabmo" to get the daemon running. The flash drive does not populate unless I "sudo reboot", then everything works as intended.

**Review by RobMackie — COMMENTED** [review]
Let's defer this pr until after PR#901 is merged. I'll rewrite on top of Jesse's changes.

**Comment by RobMackie** [comment]
Le'ts just drop this pr without merging it.

**Pull request closed without merging**
