### PR TITLE
Ssid tracks ip on bullseye and shopbotsupport.zip generation

### PR DESCRIPTION
**Pull request by RobMackie**
This pull request brings together the things needed to go with the new Raspberry Pi Linux image: 2022_rpi4-21-Bullseye-Dev-frm8G.zip. 

There are two areas of functionality included:
1) Some changes and reorganization of the network.js to bring the code that tacks the eth0 ip address onto the SSID, needed to get it to work with the newer image utilitites.
2) the introduction of "collect_and_export_data_to_usb_drive" a perl script that can collect diagnostic data and build a zip file on a usb drive if triggered by a text file on the usb drive.

Using: 2022_rpi4-21-Bullseye-Dev-frm8G.zip.
Proposed tests that describe the expected behaviors:

**test 1:**
Load this branch
Take an empty USB thumb drive
Create a file named: shopbotsupport.txt in the root directory of the thumb drive. 
Insert the thumb drive in the running pi. 
Wait for the thumb drive to be unmounted (you can just wait 4 or 5 minutes to give the process time to write out all the files or you can monitor it - my thumb drive has a light that goes out when it is  unmounted or you can ssh in and look by doing
"mount | grep media" or "ls /media/pi" if /media/pi is an empty directory, the thumb drive has been unmounted

Then explore the contents of the zip file on  your pc. (the log file that Josh pointed out needs to be there is missing. we can add it as the first "bug" against this function.

**test 2**
Do the same as test 1 but without a the file shopbotsupport.txt on the thumb. The thumb should mount and remain mounted until manually unmounted

**test 3** 
Do the same but with a file named network.txt instead of shopbotsupport.txt. Look at the contents of network.txt after completion. Should contain network info.

**test 4** 
Put both files on the thumb, should populate the network.txt file and should create the shopbotsupport.zip file.

**test 5** 
Use master to show that while using: 2022_rpi4-21-Bullseye-Dev-frm8G.zip things work out if there is no //fabmo/bin/collect_and_export_data_to_usb_drive script. (should work as does the case with no trigger files (network.txt / shopbotsupport.txt  as in test 2.

### CODE REVIEW

**Comment by kyle-kingsbury** [comment]
I started reviewing this but hit some snags. Had to change export_network_config_thumb.sh in /home/pi/bin, line 37 
from if [ ! -d /media/pi/$THUMB_DIR_MOUNT ]
to if [ ! -d "/media/pi/$THUMB_DIR_MOUNT" ]
in order to get the USB to mount correctly. After that I still could not complete test 1. Asked Rob to review and test further.

**Comment by RobMackie** [comment]
I think you can give this another try. When you run "npm run dev" it is now meant to deploy the files out out of /ffabmo/files and activate the services needed (except it won't run fabmo as a daemon since you're about to run it in develloper mode. but it'll set it up to work when you reboot or restart it with systemctl)

The bug with volume names with spaces should be dealth with now.

**Comment by kyle-kingsbury** [comment]
Still having connectivity issues. Cannot tell what is wrong. If anyone else wants to try their hand at it while I am troubleshooting that would be great.

**Comment by kyle-kingsbury** [comment]
Forgot to close branch after squash and merge.

**Pull request merged**
