### PR TITLE
Update Docker support to enable dev on current macOS

### PR DESCRIPTION
**Pull request by obra**
This is a first-pass update of the Docker configuration for FabMo-Engine to enable local development but testing FabMo in a Docker container.

Recent releases of macOS no longer allow users to create the /fabmo directory without disabling system integrity protection. That makes setting up a local fabmo dev environment on macOS challenging.

This PR gets *close* to a running FabMo dev environment with everything running in raspbian-flavored docker container.

You'll find your fabmo server running at http://localhost:8411/

It's still not quite right. As of right now, fabmo starts up, but is clearly missing a bunch of configuration. No apps show up in the UI, although login does work. Someone who knows fabmo better than me can likely tell me what I'm not yet doing.

Startup can absolutely be made faster and cleaner.

### CODE REVIEW

**Review by RobMackie — APPROVED** [review]
This seems like a much needed refactor in many ways. Looks good at the scripting and factoring level.

**Review by RobMackie — COMMENTED** [review]
Curious as to what you do to stop and start fabmo and other services inside of docker?

**Comment by RobMackie** [comment]
Merged master into this before inspection and testing. Small changes to the changed files, none that caused a problem.

I read the scripts and the package.json carefully. I ran through a clean install and run dev on the pi. I did not test this in docker. Assuming it works. May try it soon.

Ran all the normal dev-checks on pi and didn't detect an regressions

**Comment by obra** [comment]
> Curious as to what you do to stop and start fabmo and other services inside of docker?

I'm not entirely there yet. It looks like there may be some magic required to get systemd happily running in a docker container, especially running on macos where various bits of the system can't be bridged to the host.

 This is enough to get the fabmo UI up and running in docker again, but not (yet) a full environment.

It looks like in dev, the fabmo daemon gets started up by one of these package.json targets:

```
    "start": "node server.js",
    "debug": "node server.js --debug ",
    "debugserver": "node server.js --debug",
```

**Pull request merged**
